In [51]:
import pandas as pd
import numpy as np

In [52]:
df = pd.read_excel("ilpd.xlsx", names=['Age', 'Gender', 'TB', 'DB', 'Alkphos', 'Sgpt', 'Sgot', 'TP', 'ALB', 'A/G Ration'], index_col=False)

/var/folders/x1/vmgj69g51xgbn4fgdlm5lb800000gn/T/ipykernel_25307/3714812046.py:1: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_excel("ilpd.xlsx", names=['Age', 'Gender', 'TB', 'DB', 'Alkphos', 'Sgpt', 'Sgot', 'TP', 'ALB', 'A/G Ration'], index_col=False)

In [53]:
df

     Age Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB  A/G Ration
0     62   Male  10.9  5.5      699    64   100  7.5  3.2        0.74
1     62   Male   7.3  4.1      490    60    68  7.0  3.3        0.89
2     58   Male   1.0  0.4      182    14    20  6.8  3.4        1.00
3     72   Male   3.9  2.0      195    27    59  7.3  2.4        0.40
4     46   Male   1.8  0.7      208    19    14  7.6  4.4        1.30
..   ...    ...   ...  ...      ...   ...   ...  ...  ...         ...
577   60   Male   0.5  0.1      500    20    34  5.9  1.6        0.37
578   40   Male   0.6  0.1       98    35    31  6.0  3.2        1.10
579   52   Male   0.8  0.2      245    48    49  6.4  3.2        1.00
580   31   Male   1.3  0.5      184    29    32  6.8  3.4        1.00
581   38   Male   1.0  0.3      216    21    24  7.3  4.4        1.50

[582 rows x 10 columns]

In [54]:
df.isnull().sum()

Age           0
Gender        0
TB            0
DB            0
Alkphos       0
Sgpt          0
Sgot          0
TP            0
ALB           0
A/G Ration    4
dtype: int64

In [55]:
df["A/G Ration"].median()

0.94

In [56]:
df["A/G Ration"].fillna(df["A/G Ration"].median(), inplace=True)

/var/folders/x1/vmgj69g51xgbn4fgdlm5lb800000gn/T/ipykernel_25307/316612476.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["A/G Ration"].fillna(df["A/G Ration"].median(), inplace=True)

In [57]:
df.isnull().sum()

Age           0
Gender        0
TB            0
DB            0
Alkphos       0
Sgpt          0
Sgot          0
TP            0
ALB           0
A/G Ration    0
dtype: int64

In [70]:
newArray = np.array([5, 2, 3, 4, 5, 6])
sortedArray = np.argsort(newArray)
sortedArray
lexSort = np.lexsort(newArray)
lexSort

0

In [59]:
df

     Age Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB  A/G Ration
0     62   Male  10.9  5.5      699    64   100  7.5  3.2        0.74
1     62   Male   7.3  4.1      490    60    68  7.0  3.3        0.89
2     58   Male   1.0  0.4      182    14    20  6.8  3.4        1.00
3     72   Male   3.9  2.0      195    27    59  7.3  2.4        0.40
4     46   Male   1.8  0.7      208    19    14  7.6  4.4        1.30
..   ...    ...   ...  ...      ...   ...   ...  ...  ...         ...
577   60   Male   0.5  0.1      500    20    34  5.9  1.6        0.37
578   40   Male   0.6  0.1       98    35    31  6.0  3.2        1.10
579   52   Male   0.8  0.2      245    48    49  6.4  3.2        1.00
580   31   Male   1.3  0.5      184    29    32  6.8  3.4        1.00
581   38   Male   1.0  0.3      216    21    24  7.3  4.4        1.50

[582 rows x 10 columns]

In [67]:
df.sort_values(by=["Age", 'Gender'], inplace=True)

In [68]:
df

     Age  Gender    TB    DB  Alkphos  Sgpt  Sgot   TP  ALB  A/G Ration
264    4    Male   0.9   0.2      348    30    34  8.0  4.0         1.0
270    4    Male   0.8   0.2      460   152   231  6.5  3.2         0.9
217    6    Male   0.6   0.1      289    38    30  4.8  2.0         0.7
198    7  Female  27.2  11.8     1420   790  1050  6.1  2.0         0.4
479    7    Male   0.5   0.1      352    28    51  7.9  4.2         1.1
..   ...     ...   ...   ...      ...   ...   ...  ...  ...         ...
337   75    Male   1.8   0.8      405    79    50  6.1  2.9         0.9
396   78    Male   1.0   0.3      152    28    70  6.3  3.1         0.9
28    84  Female   0.7   0.2      188    13    21  6.0  3.2         1.1
43    85  Female   1.0   0.3      208    17    15  7.0  3.6         1.0
570   90    Male   1.1   0.3      215    46   134  6.9  3.0         0.7

[582 rows x 10 columns]